#!/bin/bash
# Railway Setup Script
# This script helps you configure Railway to use pre-built Docker images

echo "🚂 Railway Auto-Deploy Setup"
echo "=============================="
echo ""
echo "This script will guide you through one-time Railway configuration."
echo "After setup, every push to GitHub will auto-deploy!"
echo ""
echo "Prerequisites:"
echo "1. Railway CLI installed: npm i -g @railway/cli"
echo "2. Logged into Railway: railway login"
echo "3. Docker images pushed to Docker Hub:"
echo "   - mhassanshahbaz/doctor-assistant-backend:latest"
echo "   - mhassanshahbaz/doctor-assistant-frontend:latest"
echo ""
read -p "Press Enter to continue..."

echo ""
echo "⚠️  IMPORTANT: Railway requires manual UI configuration for Docker images."
echo ""
echo "Please do this ONE TIME in Railway Dashboard:"
echo ""
echo "BACKEND SERVICE:"
echo "1. Go to Railway Dashboard → Backend Service → Settings → Source"
echo "2. Change Build Method to: 'Docker Image'"
echo "3. Enter: mhassanshahbaz/doctor-assistant-backend:latest"
echo "4. Save"
echo ""
echo "FRONTEND SERVICE:"
echo "1. Go to Railway Dashboard → Frontend Service → Settings → Source"
echo "2. Change Build Method to: 'Docker Image'"
echo "3. Enter: mhassanshahbaz/doctor-assistant-frontend:latest"
echo "4. Save"
echo ""
echo "ENVIRONMENT VARIABLES:"
echo "Set in Railway Dashboard → Variables tab:"
echo ""
echo "Backend:"
echo "  - OPENAI_API_KEY or GROQ_API_KEY"
echo "  - JWT_SECRET_KEY"
echo "  - CORS_ORIGINS (set after frontend deploys)"
echo ""
echo "Frontend:"
echo "  - VITE_API_BASE_URL (your backend Railway URL)"
echo ""
read -p "Have you completed the manual setup? (y/n) " -n 1 -r
echo ""

if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "✅ Setup complete! Now every push will auto-deploy."
    echo ""
    echo "To test:"
    echo "  git add ."
    echo "  git commit -m 'Configure Railway'"
    echo "  git push"
    echo ""
    echo "Railway will automatically:"
    echo "  - Pull your Docker images"
    echo "  - Deploy backend and frontend"
    echo "  - No build timeouts!"
else
    echo "Please complete the manual setup first, then run this script again."
fi
